import { RowInput } from "jspdf-autotable";

export const FONT_PATH = '../../../../src/assets/font/Open_Sans/static/OpenSans_Condensed-Medium.ttf'
export const TABLE_HEADER: RowInput[] = [
    [
        { content: 'TT', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Tên SP', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Mã SP', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Loại SP', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Danh mục', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Đơn vị tính', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Khối lượng', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Doanh thu trong nước', colSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Doanh thu xuất khẩu', colSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Tổng doanh thu', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Ghi chú', rowSpan: 2, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
    ],
    [
        { content: 'Số lượng', colSpan: 1, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Doanh thu', colSpan: 1, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Số lượng', colSpan: 1, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
        { content: 'Doanh thu', colSpan: 1, styles: { font: "custom", valign: "middle", halign: "center", fontStyle: "bold" } },
    ]
]
export const PRODUCE_PRODUCT_COLUMNS: any[] = [
    {
        title: "TT",
        dataIndex: "idView",
        key: "idView",
        width: "50px",
    },
    {
        title: "Tên SP",
        dataIndex: "name",
        key: "name",
        width: "400px",
    },
    {
        title: "Mã SP",
        dataIndex: "code",
        key: "code",
        width: "200px",
    },
    {
        title: "Loại SP",
        dataIndex: "productTypeLabel",
        key: "productTypeLabel",
        width: "200px",
    },
    {
        title: "Danh mục",
        dataIndex: "productCategory",
        key: "productCategory",
        width: "400px",
    },
    {
        title: "Đơn vị tính",
        dataIndex: "unit",
        key: "unit",
        width: "150px",
    },
    {
        title: "Khối lượng",
        dataIndex: "weight",
        key: "weight",
        width: "200px",
    },
    {
        key: "domestic",
        width: "",
        title: 'Doanh thu trong nước',
        dataIndex: '',
        children: [
            {
                title: "Số lượng",
                dataIndex: 'domesticQuantity',
                key: 'domesticQuantity',
                width: "200px",
            },
            {
                title: "Doanh thu",
                dataIndex: 'domesticRevenue',
                key: 'domesticRevenue',
                width: "200px",
            },
        ]
    },
    {
        key: "export",
        width: "",
        title: 'Doanh thu xuất khẩu',
        dataIndex: '',
        children: [
            {
                title: "Số lượng",
                dataIndex: 'exportQuantity',
                key: 'exportQuantity',
                width: "200px",
            },
            {
                title: "Doanh thu",
                dataIndex: 'exportRevenue',
                key: 'exportRevenue',
                width: "200px",
            },
        ]
    },
    {
        title: "Tổng doanh thu",
        dataIndex: "totalRevenue",
        key: "totalRevenue",
        width: "200px",
    },
    {
        title: "Ghi chú",
        dataIndex: "note",
        key: "note",
        width: "200px",
    },
];
export const TABLE_DATA = [
    {
        idView: 1,
        name: "Product A",
        code: "ABC123",
        productTypeLabel: "Type 1",
        productCategory: "Category A",
        unit: "kg",
        weight: 150,
        domesticQuantity: 100,
        domesticRevenue: 5000,
        exportQuantity: 50,
        exportRevenue: 2000,
        totalRevenue: 7000000000000,
        note: "This is a note for Product A.",
        type: "product",
        children: [
            {
                idView: 1.1,
                name: "Child A",
                code: "ABC123",
                productTypeLabel: "Type 1",
                productCategory: "Category A",
                unit: "kg",
                weight: 150,
                domesticQuantity: 100,
                domesticRevenue: 5000,
                exportQuantity: 50,
                exportRevenue: 2000,
                totalRevenue: 7000,
                note: "This is a note for Product A.",
                type: "property",
            },
            {
                idView: 1.2,
                name: "Child B",
                code: "ABC123",
                productTypeLabel: "Type 1",
                productCategory: "Category A",
                unit: "kg",
                weight: 150,
                domesticQuantity: 100,
                domesticRevenue: 5000,
                exportQuantity: 50,
                exportRevenue: 2000,
                totalRevenue: 7000,
                note: "This is a note for Product A.",
                type: "property",
            },
        ]
    },
    {
        idView: 2,
        name: "Product B",
        code: "DEF456",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 80,
        domesticQuantity: 80,
        domesticRevenue: 4000,
        exportQuantity: 30,
        exportRevenue: 1500,
        totalRevenue: 5500,
        note: "This is a note for Product B.",
        type: "product"
    },
    {
        idView: 3,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 4,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 5,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 6,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 7,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 8,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 9,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 10,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 11,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 12,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 13,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 14,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 15,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 16,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 17,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 18,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
    {
        idView: 19,
        name: "Product C",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    {
        idView: 20,
        name: "Product D",
        code: "GHI789",
        productTypeLabel: "Type 1",
        productCategory: "Category C",
        unit: "liters",
        weight: 200,
        domesticQuantity: 120,
        domesticRevenue: 6000,
        exportQuantity: 70,
        exportRevenue: 3000,
        totalRevenue: 9000,
        note: "This is a note for Product C.",
        type: "product"
    },
    // Continue adding records as needed
    // ...
    {
        idView: 21,
        name: "Product J",
        code: "XYZ987",
        productTypeLabel: "Type 2",
        productCategory: "Category B",
        unit: "pieces",
        weight: 90,
        domesticQuantity: 60,
        domesticRevenue: 3000,
        exportQuantity: 40,
        exportRevenue: 1800,
        totalRevenue: 4800,
        note: "This is a note for Product J.",
        type: "product"
    },
];